# Generated by Django 4.0.8 on 2022-12-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_specialties_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skills',
            name='special',
            field=models.ManyToManyField(blank=True, related_name='special_skills', to='skills.specialties'),
        ),
    ]
