# Generated by Django 4.0.8 on 2022-12-24 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.specialties'),
        ),
        migrations.DeleteModel(
            name='Specialties',
        ),
    ]
