# Generated by Django 4.0.8 on 2022-12-24 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_employee_skills_employee_specialty'),
        ('tasks', '0002_delete_skills_alter_tasks_specialty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_tasks', to='users.employee'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_tasks', to='users.employer'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='file',
            field=models.ManyToManyField(blank=True, related_name='task_files', to='tasks.files'),
        ),
    ]
