# Generated by Django 4.1.1 on 2022-12-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="user_image", verbose_name="Image"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                default=998901321922, max_length=13, unique=True, verbose_name="Phone"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.IntegerField(
                choices=[(1, "EMPLOYEE"), (2, "EMPLOYER")], default=1
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name of User"),
        ),
    ]
