# Generated by Django 4.1.1 on 2022-12-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers_remove_user_username_user_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.IntegerField(
                choices=[(1, "EMPLOYEE"), (2, "EMPLOYER")], default=1
            ),
        ),
    ]
