# Generated by Django 4.0.8 on 2022-12-24 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('users', '0004_employer_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(related_name='skills', to='skills.skills'),
        ),
        migrations.AddField(
            model_name='employee',
            name='specialty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='skills.specialties'),
            preserve_default=False,
        ),
    ]
