# Generated by Django 4.0.8 on 2022-12-24 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_employee_additional_phone_employee_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
