# Generated by Django 4.0.8 on 2022-12-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='jins',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
