# Generated by Django 4.0.8 on 2023-07-18 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_first_name_user_last_name_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
